[package]
categories = ["embedded", "no-std", "hardware-support", "network-programming"]
name = "stm32-eth"
description = "Embedded Rust Ethernet driver for the STM32 MCU series"
license = "Apache-2.0"
authors = ["Astro <astro@spaceboyz.net>"]
version = "0.1.2"
keywords = ["ethernet", "eth", "stm32", "stm32f4"]
repository = "https://github.com/stm32-rs/stm32-eth"
documentation = "https://docs.rs/stm32-eth/"
edition = "2018"

[badges]
travis-ci = { repository = "astro/stm32-eth", branch = "master" }
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = [ "smoltcp-phy", "nucleo-f429zi" ]

[dependencies]
volatile-register = "0.2"
aligned = "0.3"
#stm32f4xx-hal = "0.6"
#smoltcp = { version = "0.5.0", default-features = false, features = ["proto-ipv4", "proto-ipv6", "socket-icmp", "socket-udp", "socket-tcp", "log", "verbose"], optional = true }
log = { version = "0.4", optional = true }

[dependencies.stm32f4xx-hal]
default-features = false
features = ["rt", "stm32f429"]
git = "https://github.com/jonlamb-gh/stm32f4xx-hal.git"
branch = "home-phone-changes"

[dependencies.smoltcp]
#version = "0.5.0"
git = "https://github.com/m-labs/smoltcp.git"
branch = "master"
default-features = false
features = [
    "ethernet",
    "proto-ipv4",
    "proto-ipv6",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "log",
    "verbose"
]
optional = true

[features]
smoltcp-phy = ["smoltcp", "log"]
default = []
nucleo-f429zi = ["stm32f4xx-hal/stm32f429"]

[dev-dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
panic-itm = "0.4"

[[example]]
name = "pktgen"

[[example]]
name = "ip"
required-features = ["smoltcp-phy"]

[profile.release]
debug = 2
lto = true
